services:
  - type: web
    name: restaurante-tec-oriente
    runtime: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /